services:
  it-delivers-everywhere-qqq:
    replicas: 1
    image: mdefenders/it-delivers-everywhere
    tag: action-test-pr-32
  it-delivers-everywhere:
    replicas: 1
    image: mdefenders/it-delivers-everywhere
    tag: action-test-pr-32
